### ISSUE TITLE
Composer Install Artisan Fatal Error

### ISSUE THREAD

**Issue by jhollowe** [devfake/flox#115]
After cloning the master branch, installing dependencies, and running `composer install` in `flox/backend/` the following error is thrown on Alpine 3.10:
```
flox-host:/opt/flox/backend# composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> Illuminate\Foundation\ComposerScripts::postInstall
> php artisan optimize
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Class 'PDO' not found in /opt/flox/backend/config/database.php:16
Stack trace:
#0 /opt/flox/backend/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(60): require()
#1 /opt/flox/backend/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/LoadConfiguration.php(38): Illuminate\Foundation\Bootstrap\LoadConfiguration->loadConfigurationFiles(Object(Illuminate\Foundation\Application), Object(Illuminate\Config\Repository))
#2 /opt/flox/backend/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\LoadConfiguration->bootstrap(Object(Illuminate\Foundation\Application))
#3 /opt/flox/backend/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(268): Illuminate\Foundation\Application->bootstrapWith(Array)
#4 /opt/flox/backend/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(114): Illuminate\Foundation\Console\Kernel->bootstrap()
 in /opt/flox/backend/config/database.php on line 16
Script php artisan optimize handling the post-install-cmd event returned with error code 255
```

**Comment by digibucc** [comment]
I found this to be caused by not having php-pdo installed, however i still get stuck at "php artisan flox:db" as it says mysql is not configured.

edit: that just require php-mysqlnd to be installed.

**Comment by devfake** [comment]
Oh wow, i didn't see the issues here in flox :/

@jhollowe did the comment from @digibucc helped you?

**Comment by jhollowe** [comment]
I just changed to running on Ubuntu 18.04 and everything worked.
