### ISSUE TITLE
Redundancy with discrepancy

### ISSUE THREAD

**Issue by danielsatanik** [devfake/flox#95]
It seems if I search for series with different titles (title and original_title) it yields different results kind of, I added "Classroom of the elite" to my list but after some time (today) I didn't remember if I already added it so I searched for the jap title "Youkoso jitsuryoku...". It both yielded from the laravel logs apparently the same result with the same id but on the site it didn't show as already added, so when I clicked I got that endless spinning wheel (box filling up and rotating), as adding it again caused a duplicate entry violation in SQL but no error callback ends the spinning.

But the real issue here is that it didn't realise that both queries are the same series. The logs are below:

```
Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '72517' for key 'items_tmdb_id_unique' (SQL: insert into `items` (`tmdb_id`, `title`, `media_type`, `original_title`, `poster`, `rating`, `released`, `genre`, `created_at`) values (72517, Classroom of the Elite, tv, ようこそ実力至上主義の教室へ, /ok9vS2v7r4in14R9AUOtBXTwdYy.jpg, 1, 1499888046, Animation, Comedy, Drama, 1506540849)) in /var/www/flox.example.com/backend/vendor/laravel/framework/src/Illuminate/Database/Connection.php:764
Stack trace:
#0 /var/www/flox.example.com/backend/vendor/laravel/framework/src/Illuminate/Database/Connection.php(720): Illuminate\Database\Connection->runQueryCallback('insert into `it...', Array, Object(Closure))
#1 /var/www/flox.example.com/backend/vendor/laravel/framework/src/Illuminate/Database/Connection.php(481): Illuminate\Database\Connection->run('insert into `it...', Array, Object(Closure))
#2 /var/www/flox.example.com/backend/vendor/laravel/framework/src/Illuminate/Database/Connection.php(435): Illuminate\Database\Connection->statement('insert into `it...', Array)
#3 /var/www/flox.example.com/backend/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert('insert into `it...', Array)
#4 /var/www/flox.example.com/backend/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2142): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `it...', Array, 'id')
#5 [internal function]: Illuminate\Database\Query\Builder->insertGetId(Array, 'id')
#6 /var/www/flox.example.com/backend/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1441): call_user_func_array(Array, Array)
#7 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(10783): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#8 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(10772): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#9 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(10726): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#10 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(10384): Illuminate\Database\Eloquent\Model->save()
#11 /var/www/flox.example.com/backend/app/Http/Controllers/ItemController.php(161): Illuminate\Database\Eloquent\Model::create(Array)
#12 /var/www/flox.example.com/backend/app/Http/Controllers/ItemController.php(114): App\Http\Controllers\ItemController->createItem(Array, Object(App\Services\TMDB))
#13 [internal function]: App\Http\Controllers\ItemController->add(Object(App\Services\TMDB))
#14 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(9403): call_user_func_array(Array, Array)
#15 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(8459): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(App\Http\Controllers\ItemController), 'add')
#16 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(8440): Illuminate\Routing\Route->runController()
#17 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(8149): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#18 /var/www/flox.example.com/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(9967): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(9859): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /var/www/flox.example.com/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /var/www/flox.example.com/backend/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(9859): Illuminate\Auth\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /var/www/flox.example.com/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(3151): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(9859): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /var/www/flox.example.com/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(13459): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(9859): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /var/www/flox.example.com/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(11899): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(9859): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /var/www/flox.example.com/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(13205): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(9859): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /var/www/flox.example.com/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(13142): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(9859): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /var/www/flox.example.com/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(9844): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(8150): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#42 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(8141): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#43 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(8132): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#44 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(2472): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#45 /var/www/flox.example.com/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#46 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(3213): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(9859): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /var/www/flox.example.com/backend/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(33): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(9844): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(2416): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#51 /var/www/flox.example.com/backend/bootstrap/cache/compiled.php(2400): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#52 /var/www/flox.example.com/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#53 {main}
```

And here is a screenshot of the not added and the added one

![screenshot](https://user-images.githubusercontent.com/2507586/30934341-94abb8d4-a3cd-11e7-9f38-439e8a8982fd.jpg)

![screen shot 2017-09-27 at 21 48 47](https://user-images.githubusercontent.com/2507586/30934370-b05bc09c-a3cd-11e7-863d-7ce78b8a05e6.jpeg)

**Comment by devfake** [comment]
In version 2 of flox we have already made a few changes that prevent such behavior. 

Another reason could be when TMDb inserts new titles that are not yet stored in the flox instance. Version 2 will also offer a solution for this problem.

Thank you for this issue :)

**Comment by danielsatanik** [comment]
@devfake Just a follow up question, is it save to upgrade to version 2 already? and how would this work?
